name: Update opcodes

on:
  schedule:
    # At minute 0 past every 4th hour.
    - cron: "0 */4 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download opcodes
        run: |
          wget -O ./scripts/opcodes/FFXIVNetworkOpcodes.zip https://github.com/moewcorp/FFXIVNetworkOpcodes/archive/refs/heads/master.zip
          cd ./scripts/opcodes
          unzip FFXIVNetworkOpcodes.zip
          cp -r FFXIVNetworkOpcodes-master/output .
          rm -rf FFXIVNetworkOpcodes.zip FFXIVNetworkOpcodes-master
        shell: bash

      - name: Install poetry
        run: pipx install poetry
        shell: bash

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "poetry"

      - run: poetry install
        shell: bash

      - run: poetry run python scripts/update_opcode.py
        shell: bash

      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "chore(opcode): update opcodes"
          git push
